### ISSUE TITLE
Building with `--shared-libs` does not work anymore

### ISSUE THREAD

**Issue by keryell** [intel/llvm#10170]
**Describe the bug**

When the compiler and tools are compiled with `--shared-libs` there is a runtime error.
For example:
```
$DPCPP_HOME/llvm/build/bin/sycl-ls
sycl-ls: /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/llvm/include/llvm/Support/CommandLine.h:864: void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*)]: Assertion `findOption(Name) == Values.size() && "Option already exists!"' failed.
Aborted (core dumped)
```

**To Reproduce**
Compiled with shared library
```
python3 $DPCPP_HOME/llvm/buildbot/configure.py --cuda \
  --shared-libs --cmake-opt="-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
python3 $DPCPP_HOME/llvm/buildbot/compile.py
$DPCPP_HOME/llvm/build/bin/sycl-ls
sycl-ls: /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/llvm/include/llvm/Support/CommandLine.h:864: void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*)]: Assertion `findOption(Name) == Values.size() && "Option already exists!"' failed.
Aborted (core dumped)
```

Compiled without shared library
```
python3 $DPCPP_HOME/llvm/buildbot/configure.py --cuda \
  --cmake-opt="-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
python3 $DPCPP_HOME/llvm/buildbot/compile.py
$DPCPP_HOME/llvm/build/bin/sycl-ls
[opencl:cpu:0] Intel(R) CPU Runtime for OpenCL(TM) Applications, Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz OpenCL 2.1 (Build 0) [18.1.0.0920]
[opencl:cpu:1] Portable Computing Language, pthread-haswell-Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz OpenCL 3.0 PoCL HSTR: pthread-x86_64-pc-linux-gnu-haswell [3.1+debian]
[ext_oneapi_cuda:gpu:0] NVIDIA CUDA BACKEND, Quadro P3200 6.1 [CUDA 12.1]
```

**Environment (please complete the following information):**

- OS: Ubuntu 23.04

**Additional context**

This problem is not recent and has been there for a few months.

**Comment by bader** [comment]
Interesting... we build the configuration with shared libraries for each commit, and I don't see issues like this in the logs (note: we use Ubuntu 22.04). In your case it looks like some of LLVM libraries are still linked statically to sycl-ls tool.
What commit do you build?

**Comment by bader** [comment]
I tried it locally and I can't reproduce this issue with a8b03562c5f3f32d581c602724d75f5c49eb1fec.

**Comment by keryell** [comment]
That is curious. I will try on my personal laptop with Debian/unstable to compare.

**Comment by ph0b** [comment]
It could be a symbols compatibility issue, with some LLVM ones coming from a different source than when compiling statically. Running with `LD_DEBUG=bindings` in the good and bad cases can help.

**Comment by keryell** [comment]
Thanks. I still need to find some time to investigate.

**Comment by keryell** [comment]
Looking from GDB, it looks like the PoCL on my system uses a dynamic library from the compiled SYCL compiler instead of the expected LLVM one from the system for PoCL:
```
rkeryell@rk-xsj:~/Xilinx/Projects/Khronos/SYCL/muSYCL/build/src (master)$ LD_LIBRARY_PATH=$DPCPP_HOME/llvm/build/lib gdb $DPCPP_HOME/llvm/build/bin/sycl-ls
GNU gdb (Ubuntu 13.1-2ubuntu2) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/bin/sycl-ls...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) n
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
(No debugging symbols found in /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/bin/sycl-ls)
(gdb) r
Starting program: /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/bin/sycl-ls 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
sycl-ls: /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/llvm/include/llvm/Support/CommandLine.h:864: void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*)]: Assertion `findOption(Name) == Values.size() && "Option already exists!"' failed.

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff723c406 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff722287c in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff722279b in __assert_fail_base (fmt=0x7ffff73b9f68 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff3bd6c68 "findOption(Name) == Values.size() && \"Option already exists!\"", 
    file=file@entry=0x7ffff3bd6110 "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/llvm/include/llvm/Support/CommandLine.h", line=line@entry=864, 
    function=function@entry=0x7ffff3c876d8 "void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* "...) at ./assert/assert.c:92
#6  0x00007ffff7233b86 in __assert_fail (
    assertion=0x7ffff3bd6c68 "findOption(Name) == Values.size() && \"Option already exists!\"", 
    file=0x7ffff3bd6110 "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/llvm/include/llvm/Support/CommandLine.h", line=864, 
    function=0x7ffff3c876d8 "void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* "...) at ./assert/assert.c:101
#7  0x00007ffff385355a in llvm::RegisterPassParser<llvm::MachineSchedRegistry>::NotifyAdd(llvm::StringRef, llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*), llvm::StringRef) ()
   from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libLLVMCodeGen.so.18git
#8  0x00007fffe479e7f3 in ?? () from /lib/x86_64-linux-gnu/libLLVM-15.so.1
#9  0x00007ffff7fcd33e in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffddb8, 
    env=env@entry=0x7fffffffddc8) at ./elf/dl-init.c:70
#10 0x00007ffff7fcd428 in call_init (env=0x7fffffffddc8, argv=0x7fffffffddb8, argc=1, l=<optimized out>)
    at ./elf/dl-init.c:33
--Type <RET> for more, q to quit, c to continue without paging--
#11 _dl_init (main_map=0x5555556118c0, argc=1, argv=0x7fffffffddb8, env=0x7fffffffddc8) at ./elf/dl-init.c:117
#12 0x00007ffff7fc9562 in __GI__dl_catch_exception (exception=exception@entry=0x0, operate=operate@entry=0x7ffff7fd4290 <call_dl_init>, args=args@entry=0x7fffffffd180) at ./elf/dl-catch.c:211
#13 0x00007ffff7fd4346 in dl_open_worker (a=0x7fffffffd320) at ./elf/dl-open.c:808
#14 dl_open_worker (a=a@entry=0x7fffffffd320) at ./elf/dl-open.c:771
#15 0x00007ffff7fc94dd in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffd300, operate=operate@entry=0x7ffff7fd42b0 <dl_open_worker>, args=args@entry=0x7fffffffd320) at ./elf/dl-catch.c:237
#16 0x00007ffff7fd46bc in _dl_open (file=0x555555611870 "libpocl.so.2.10.0", mode=<optimized out>, caller_dlopen=0x7ffff589aac4 <khrIcdOsLibraryLoad+20>, nsid=<optimized out>, argc=1, argv=0x7fffffffddb8, 
    env=0x7fffffffddc8) at ./elf/dl-open.c:884
#17 0x00007ffff728abec in dlopen_doit (a=a@entry=0x7fffffffd590) at ./dlfcn/dlopen.c:56
#18 0x00007ffff7fc94dd in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffd4f0, operate=0x7ffff728ab90 <dlopen_doit>, args=0x7fffffffd590) at ./elf/dl-catch.c:237
#19 0x00007ffff7fc9603 in _dl_catch_error (objname=0x7fffffffd548, errstring=0x7fffffffd550, mallocedp=0x7fffffffd547, operate=<optimized out>, args=<optimized out>) at ./elf/dl-catch.c:256
#20 0x00007ffff728a6bf in _dlerror_run (operate=operate@entry=0x7ffff728ab90 <dlopen_doit>, args=args@entry=0x7fffffffd590) at ./dlfcn/dlerror.c:138
#21 0x00007ffff728aca1 in dlopen_implementation (dl_caller=<optimized out>, mode=<optimized out>, file=<optimized out>) at ./dlfcn/dlopen.c:71
#22 ___dlopen (file=<optimized out>, mode=<optimized out>) at ./dlfcn/dlopen.c:81
#23 0x00007ffff589aac4 in khrIcdOsLibraryLoad () from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libOpenCL.so.1
#24 0x00007ffff58945bd in khrIcdVendorAdd.localalias () from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libOpenCL.so.1
#25 0x00007ffff589a716 in khrIcdOsVendorsEnumerate () from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libOpenCL.so.1
#26 0x00007ffff72942e7 in __pthread_once_slow (once_control=0x7ffff589f5e8 <initialized>, init_routine=0x7ffff589a1c0 <khrIcdOsVendorsEnumerate>) at ./nptl/pthread_once.c:116
#27 0x00007ffff5895ad5 in clGetPlatformIDs () from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libOpenCL.so.1
#28 0x00007ffff7f9134d in piPlatformsGet () from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libpi_opencl.so
#29 0x00007ffff7d01fb2 in sycl::_V1::detail::platform_impl::get_platforms()::{lambda(std::shared_ptr<sycl::_V1::detail::plugin>&)#1}::operator()(std::shared_ptr<sycl::_V1::detail::plugin>&) const [clone .constprop.0] () from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libsycl.so.7
#30 0x00007ffff7d0864f in sycl::_V1::detail::platform_impl::get_platforms() () from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libsycl.so.7
#31 0x00007ffff7df2471 in sycl::_V1::platform::get_platforms() () from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/build/lib/libsycl.so.7
#32 0x0000555555556b2e in main ()
```
Interesting. :-)
I have removed the `libpocl2` package from my Ubuntu 23.04 laptop and now it works.
I guess this is a packaging issue where for safety any loadable OpenCL implementation should be statically linked to avoid conflicts when used from an application using different versions of library than the default one on the system.
That sounds sub-optimal but is there another solution?
Any feedback @pjaaskel, @bashbaug, @Kerilk.

**Comment by pjaaskel** [comment]
@keyell, If I understand the issue right, this is related to LLVM packaging, not OpenCL packaging. PoCL expects the upstream-compatible LLVM to be found as libLLVM*.so (packaged by Ubuntu/Debian/apt.llvm.org). If something non-compatible claims the same library name and PoCL accidentally links to it (or vice versa), Things Can Happen, of course. If Intel's LLVM branch is not compatible with the upstream, I suggest renaming the libraries to libLLVM-Intel*.so or such to avoid this type of conflicts and enable safe use of LLVM via dynlibs.
