### ISSUE TITLE
[SYCL][OpenCL] Building with debug info crashes OpenCL CPU JIT

### ISSUE THREAD

**Issue by joeatodd** [intel/llvm#10448]
**Describe the bug**
Building SYCL kernels with debug info for OpenCL CPU causes runtime JIT crashes.

**To Reproduce**
``` c++
#include <sycl/sycl.hpp>

int main(){
  sycl::queue q{};
  q.single_task([](){});
}
```
Build and run:
``` bash
clang++ -fsycl -g -fsycl-targets=spir64 mwe.cpp 
ONEAPI_DEVICE_SELECTOR=opencl:cpu ./a.out
```
Produces a segfault with the following backtrace:
```
#0  0x00007fb6a9b21264 in ?? () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libclang_compiler.so.2022.13.3.0
#1  0xdaef9c77f9a36c00 in ?? ()
#2  0x00000000025a74b0 in ?? ()
#3  0x000000000000000d in ?? ()
#4  0x037f0f7f077fd89a in ?? ()
#5  0xdaef9c77f9a36c00 in ?? ()
#6  0x000000000278a988 in ?? ()
#7  0x00000000026f86a0 in ?? ()
#8  0x0000000000000003 in ?? ()
#9  0x00000000027b7690 in ?? ()
#10 0x00007fb6a9fc87a4 in llvm::MDNode* SPIRV::SPIRVToLLVMDbgTran::transDebugInst<llvm::MDNode>(SPIRV::SPIRVExtInst const*) () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libclang_compiler.so.2022.13.3.0
#11 0x00007fb6a9fc81df in SPIRV::SPIRVToLLVM::translate() () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libclang_compiler.so.2022.13.3.0
#12 0x00007fb6a9fd351d in llvm::convertSpirvToLLVM(llvm::LLVMContext&, SPIRV::SPIRVModule&, SPIRV::TranslatorOpts const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
   from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libclang_compiler.so.2022.13.3.0
#13 0x00007fb6a9fd3fe0 in llvm::readSpirv(llvm::LLVMContext&, SPIRV::TranslatorOpts const&, std::istream&, llvm::Module*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
   from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libclang_compiler.so.2022.13.3.0
#14 0x00007fb6a9c8ef59 in Intel::OpenCL::ClangFE::ClangFECompilerParseSPIRVTask::ParseSPIRV(Intel::OpenCL::ClangFE::IOCLFEBinaryResult**) () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libclang_compiler.so.2022.13.3.0
#15 0x00007fb6a9c88662 in Intel::OpenCL::ClangFE::ClangFECompiler::ParseSPIRV(Intel::OpenCL::FECompilerAPI::FESPIRVProgramDescriptor*, Intel::OpenCL::ClangFE::IOCLFEBinaryResult**) () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libclang_compiler.so.2022.13.3.0
#16 0x00007fb6cfd1463a in Intel::OpenCL::Framework::FrontEndCompiler::ParseSpirv(char const*, unsigned int, char const*, unsigned long, unsigned int const*, unsigned long const*, char**, unsigned long*, char**) const ()
   from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#17 0x00007fb6cfccacef in Intel::OpenCL::Framework::CompileTask::Execute() () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#18 0x00007fb6cfccb18d in non-virtual thunk to Intel::OpenCL::Framework::CompileTask::Execute() () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#19 0x00007fb6f8195082 in Intel::OpenCL::TaskExecutor::execute_command(Intel::OpenCL::Utils::SharedPtr<Intel::OpenCL::TaskExecutor::ITaskBase> const&, Intel::OpenCL::TaskExecutor::base_command_list&) ()
   from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libtask_executor.so.2022.13.3.0
#20 0x00007fb6f81823aa in tbb::detail::d1::task_arena_function<Intel::OpenCL::TaskExecutor::immediate_executor_task, void>::operator()() const () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libtask_executor.so.2022.13.3.0
#21 0x00007fb6e01af369 in tbb::detail::r1::task_arena_impl::execute (ta=..., d=warning: RTTI symbol not found for class 'SPIRV::SPIRVExtInst'
...) at /localdisk/ci/runner006/intel-innersource/001/_work/libraries.threading.infrastructure.onetbb-ci/libraries.threading.infrastructure.onetbb-ci/onetbb_source_code/src/tbb/arena.cpp:698
#22 0x00007fb6f8180aa3 in Intel::OpenCL::TaskExecutor::immediate_command_list::LaunchExecutorTask(bool, Intel::OpenCL::Utils::SharedPtr<Intel::OpenCL::TaskExecutor::ITaskBase> const&) () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libtask_executor.so.2022.13.3.0
#23 0x00007fb6cfc7f6a6 in Intel::OpenCL::Framework::FrameworkProxy::ExecuteImmediate(Intel::OpenCL::Utils::SharedPtr<Intel::OpenCL::TaskExecutor::ITaskBase> const&) const () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#24 0x00007fb6cfcca159 in Intel::OpenCL::Framework::BuildTask::Launch() () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#25 0x00007fb6cfcd32b2 in Intel::OpenCL::Framework::ProgramService::BuildProgram(Intel::OpenCL::Utils::SharedPtr<Intel::OpenCL::Framework::Program> const&, unsigned int, _cl_device_id* const*, char const*, void (*)(_cl_program*, void*), void*) ()
   from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#26 0x00007fb6cfcae86a in Intel::OpenCL::Framework::Context::BuildProgram(_cl_program*, unsigned int, _cl_device_id* const*, char const*, void (*)(_cl_program*, void*), void*) () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#27 0x00007fb6cfc8ffac in Intel::OpenCL::Framework::ContextModule::BuildProgram(_cl_program*, unsigned int, _cl_device_id* const*, char const*, void (*)(_cl_program*, void*), void*) () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#28 0x00007fb6cfc39505 in clBuildProgram () from /opt/intel/oclcpuexp-2022.13.3.0.16_rel/x64/libintelocl.so
#29 0x00007fb6fb367026 in sycl::_V1::detail::ProgramManager::build(std::unique_ptr<_pi_program, _pi_result (*)(_pi_program*)>, std::shared_ptr<sycl::_V1::detail::context_impl>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _pi_device* const&, unsigned int) () from /home/joe/soft/llvm/lib/libsycl.so.7
#30 0x00007fb6fb369ee5 in sycl::_V1::detail::ProgramManager::getBuiltPIProgram(std::shared_ptr<sycl::_V1::detail::context_impl> const&, std::shared_ptr<sycl::_V1::detail::device_impl> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, sycl::_V1::detail::program_impl const*, bool) () from /home/joe/soft/llvm/lib/libsycl.so.7
#31 0x00007fb6fb3727b6 in sycl::_V1::detail::ProgramManager::getOrCreateKernel(std::shared_ptr<sycl::_V1::detail::context_impl> const&, std::shared_ptr<sycl::_V1::detail::device_impl> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, sycl::_V1::detail::program_impl const*) () from /home/joe/soft/llvm/lib/libsycl.so.7
#32 0x00007fb6fb3a76d2 in sycl::_V1::detail::enqueueImpKernel(std::shared_ptr<sycl::_V1::detail::queue_impl> const&, sycl::_V1::detail::NDRDescT&, std::vector<sycl::_V1::detail::ArgDesc, std::allocator<sycl::_V1::detail::ArgDesc> >&, std::shared_ptr<sycl::_V1::detail::kernel_bundle_impl> const&, std::shared_ptr<sycl::_V1::detail::kernel_impl> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<_pi_event*, std::allocator<_pi_event*> >&, _pi_event**, std::function<void* (sycl::_V1::detail::AccessorImplHost*)> const&, _pi_kernel_cache_config) () from /home/joe/soft/llvm/lib/libsycl.so.7
#33 0x00007fb6fb3f1ab7 in sycl::_V1::handler::finalize()::{lambda()#1}::operator()() const () from /home/joe/soft/llvm/lib/libsycl.so.7
#34 0x00007fb6fb3f84b1 in sycl::_V1::handler::finalize() () from /home/joe/soft/llvm/lib/libsycl.so.7
#35 0x00007fb6fb4197fb in sycl::_V1::detail::queue_impl::submit_impl(std::function<void (sycl::_V1::handler&)> const&, std::shared_ptr<sycl::_V1::detail::queue_impl> const&, std::shared_ptr<sycl::_V1::detail::queue_impl> const&, std::shared_ptr<sycl::_V1::detail::queue_impl> const&, sycl::_V1::detail::code_location const&, std::function<void (bool, bool, sycl::_V1::event&)> const*) () from /home/joe/soft/llvm/lib/libsycl.so.7
#36 0x00007fb6fb419ec0 in sycl::_V1::queue::submit_impl(std::function<void (sycl::_V1::handler&)>, sycl::_V1::detail::code_location const&) () from /home/joe/soft/llvm/lib/libsycl.so.7
#37 0x00000000004038ce in _ZN4sycl3_V15queue6submitIZNS1_11single_taskINS0_6detail9auto_nameEZ4mainEUlvE_NS0_3ext6oneapi12experimental10propertiesISt5tupleIJEEEEEENSt9enable_ifIXsr3ext6oneapi12experimental16is_property_listIT1_EE5valueENS0_5eventEE4typeESF_RKT0_RKNS4_13code_locationEEUlRNS0_7handlerEE_EESG_T_SO_ ()
#38 0x0000000000403811 in sycl::_V1::queue::single_task<sycl::_V1::detail::auto_name, main::{lambda()#1}, sycl::_V1::ext::oneapi::experimental::properties<std::tuple<> > > ()
#39 0x00000000004036c9 in sycl::_V1::event sycl::_V1::queue::single_task<sycl::_V1::detail::auto_name, main::{lambda()#1}>(main::{lambda()#1} const&, sycl::_V1::detail::code_location const&) ()
#40 0x0000000000403620 in main ()
```

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: Intel CPU
- DPC++ version: `21ca00fb1cc5408b2428e3c386aa5137ed551fdb` (tested on various recent versions)
- Dependencies version: OpenCL Runtime Version (various tested) `2022.13.3.0.16_rel`, `2023.15.3.0.20_160000`, `2023.2`

This issue was introduced **some time in the last ~6 months**. Last known good commit: `751acf357ed192a2f9de5171ccdf4a69510cff37`

**Comment by AlexeySachkov** [comment]
Tagging @MrSidims for awareness: looking at the backtrace, the issue should be reproducible with SPIR-V translator alone

**Comment by maarquitos14** [comment]
Not reproducible.
