### ISSUE TITLE
gmake[1]: *** [tools/sycl/CMakeFiles/deploy-sycl-toolchain.dir/rule] Error 2

### ISSUE THREAD

**Issue by spadesw** [intel/llvm#11558]
I get an error when I run the instruction as follow:
```shell
CUDA_LIB_PATH=/home/wangzhong123/cuda-11.6/lib64/stubs CC=gcc CXX=g++ python $DPCPP_HOME/llvm/buildbot/compile.py
```
And it returns:
```shell
gmake[1]: *** [tools/sycl/CMakeFiles/deploy-sycl-toolchain.dir/rule] Error 2
gmake: *** [deploy-sycl-toolchain] Error 2
Traceback (most recent call last):
  File "/home/wangzhong123/sycl_workspace/llvm/buildbot/compile.py", line 71, in <module>
    ret = main()
  File "/home/wangzhong123/sycl_workspace/llvm/buildbot/compile.py", line 67, in main
    return do_compile(args)
  File "/home/wangzhong123/sycl_workspace/llvm/buildbot/compile.py", line 42, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/wangzhong123/sycl_workspace/llvm/build', '--', 'deploy-sycl-toolchain', '-j', '56']' returned non-zero exit status 2
```

**Comment by maarquitos14** [comment]
@spadesw could you try using Python3? If that fails too, then, could you try running the build command manually, rather than using the `compile.py` script and pasting the output? Based on your output, the build command is:
`cmake --build /home/wangzhong123/sycl_workspace/llvm/build -- deploy-sycl-toolchain -j 56`.

**Comment by KornevNikita** [comment]
@spadesw any updates?
