### ISSUE TITLE
cl::sycl::buffer getting stuck after parallel_for calculation

### ISSUE THREAD

**Issue by krasznaa** [intel/llvm#1251]
Hi,

The following may very well just be me not understanding how the code should be written, but I still find the current behaviour of my compiled executable very confusing. Take the following simple example code:

```c++
// SYCL include(s).
#include <CL/sycl.hpp>

// System include(s).
#include <cmath>
#include <iostream>

int main() {

   // Set up a SYCL buffer on top of this STL object.
   static const std::size_t ARRAY_SIZE = 10000;
   static const float ARRAY_ELEMENT = 3.141592f;
   cl::sycl::buffer< cl::sycl::cl_float, 1 > buffer( ARRAY_SIZE );
   auto bWriter = buffer.get_access< cl::sycl::access::mode::write >();
   for( std::size_t i = 0; i < buffer.get_count(); ++i ) {
      bWriter[ i ] = ARRAY_ELEMENT;
   }

   // Set up the SYCL queue.
   cl::sycl::host_selector deviceSelector;
   cl::sycl::queue queue( deviceSelector );
   cl::sycl::range< 1 > workItems( buffer.get_count() );

   // Let the user know what device the calculation is running on.
   const cl::sycl::device& device = queue.get_device();
   std::cout << "Using device: "
             << device.get_info< cl::sycl::info::device::name >()
             << " ("
             << device.get_info< cl::sycl::info::device::version >()
             << ")" << std::endl;

   // Multiply these values using SYCL.
   static const float MULTIPLIER = 1.23f;
   queue.submit( [&]( cl::sycl::handler& handler ) {
         auto acc =
            buffer.get_access< cl::sycl::access::mode::read_write >( handler );
         handler.parallel_for< class SYCLMultiply >(
            workItems, [=]( cl::sycl::id< 1 > id ) {
               acc[ id ] *= MULTIPLIER;
            } );
      } );

   // Check the results.
   auto bReader =
      buffer.get_access< cl::sycl::access::mode::read >();
   static const float EXPECTED_RESULT = ARRAY_ELEMENT * MULTIPLIER;
   for( std::size_t i = 0; i < buffer.get_count(); ++i ) {
      if( std::abs( bReader[ i ] - EXPECTED_RESULT ) > 0.001 ) {
         std::cerr << "The SYCL transformation failed to run" << std::endl;
         return 1;
      }
   }
   std::cout << "The SYCL transformation succeeded" << std::endl;

   // Return gracefully.
   return 0;
}
```

When I compile/run it, I get:

```
[bash][atspot01]:sycl > ./syclLinearTransform 
Using device: SYCL host device (1.2)
```

I.e. the application gets stuck. Looking at it with GDB, I see the following:

```
(gdb) attach 8722
Attaching to process 8722
[New LWP 8730]
[New LWP 8731]
warning: File "/home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so-gdb.py
line to your configuration file "/home/krasznaa/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/krasznaa/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f469fa8e9a0 in cl::sycl::detail::Command::enqueue(cl::sycl::detail::EnqueueResultT&, cl::sycl::detail::BlockingT) ()
   from /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so
(gdb) bt
#0  0x00007f469fa8e9a0 in cl::sycl::detail::Command::enqueue(cl::sycl::detail::EnqueueResultT&, cl::sycl::detail::BlockingT) ()
   from /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so
#1  0x00007f469fa9cde6 in cl::sycl::detail::Scheduler::GraphProcessor::enqueueCommand(cl::sycl::detail::Command*, cl::sycl::detail::EnqueueResultT&, cl::sycl::detail::BlockingT) ()
   from /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so
#2  0x00007f469fa9cde6 in cl::sycl::detail::Scheduler::GraphProcessor::enqueueCommand(cl::sycl::detail::Command*, cl::sycl::detail::EnqueueResultT&, cl::sycl::detail::BlockingT) ()
   from /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so
#3  0x00007f469fa9ce99 in cl::sycl::detail::Scheduler::GraphProcessor::waitForEvent(std::shared_ptr<cl::sycl::detail::event_impl>) () from /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so
#4  0x00007f469fa97605 in cl::sycl::detail::Scheduler::waitForEvent(std::shared_ptr<cl::sycl::detail::event_impl>) ()
   from /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so
#5  0x00007f469fa2e130 in cl::sycl::detail::event_impl::wait(std::shared_ptr<cl::sycl::detail::event_impl>) const ()
   from /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so
#6  0x00007f469f864063 in cl::sycl::detail::addHostAccessorAndWait(cl::sycl::detail::AccessorImplHost*) ()
   from /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/libsycl.so
#7  0x000000000040e98b in cl::sycl::accessor<float, 1, (cl::sycl::access::mode)1024, (cl::sycl::access::target)2018, (cl::sycl::access::placeholder)0>::accessor<1, cl::sycl::detail::aligned_allocator<char>, (void*)0> (this=0x7ffde4ca2488, BufferRef=...)
    at /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/clang/11.0.0/include/CL/sycl/accessor.hpp:813
#8  0x00000000004047a3 in cl::sycl::buffer<float, 1, cl::sycl::detail::aligned_allocator<char> >::get_access<(cl::sycl::access::mode)1024> (this=0x7ffde4ca2650)
    at /home/krasznaa/Software/IntelClang/11.0.0-6cf590f/x86_64-ubuntu1804-gcc8/lib/clang/11.0.0/include/CL/sycl/buffer.hpp:248
#9  0x0000000000403110 in main () at syclLinearTransform.cxx:46
(gdb)
```

I.e. the code is stuck on the

```c++
auto bReader =
   buffer.get_access< cl::sycl::access::mode::read >();
```

call. :confused:

Now... If I set up the buffer instead like the following

```c++
      // Create a vector array that would be manipulated.
      std::vector< float > dummyArray;
      static const std::size_t ARRAY_SIZE = 10000;
      dummyArray.reserve( ARRAY_SIZE );
      static const float ARRAY_ELEMENT = 3.141592f;
      for( std::size_t i = 0; i < ARRAY_SIZE; ++i ) {
         dummyArray.push_back( ARRAY_ELEMENT );
      }

      // Set up a SYCL buffer on top of this STL object.
      cl::sycl::buffer< cl::sycl::cl_float > buffer( dummyArray.begin(),
                                                     dummyArray.end() );
```

, the code starts working. Both on the host, and on any accelerated device as well.

Is it not supposed to be possible to use buffers "on their own" as in my first example? Or is this indeed some bug in the current implementation?

Cc. @fwyzard, @cleggett

Cheers,
     Attila

**Comment by sergey-semenov** [comment]
Hi, @krasznaa 

The reason why the first code gets stuck is that you attempt to create two host accessors (one of which has write access) for the same buffer. Destroying the first accessor via scoping first will resolve the issue.

```
auto bWriter = buffer.get_access< cl::sycl::access::mode::write >();
...
auto bReader =
   buffer.get_access< cl::sycl::access::mode::read >();
```

**Comment by krasznaa** [comment]
Dear Sergey,

Very interesting. Thanks, this indeed fixes the issue!

I wonder though if it would make sense to issue a runtime warning/error when such a thing is encountered. If such a situation can reasonably be looked for in LLVM/Clang that is...

Cheers,
   Attila

**Comment by romanovvlad** [comment]
Blocking is a valid behavior that you can rely on in the multi-threaded application. If you are sure that an application you are looking at doesn't rely on the feature you can try to set SYCL_THROW_ON_BLOCK env var and see if something changes. But note, this variable is for the SYCL runtime developers, please do not rely on it in production code.

**Comment by romanovvlad** [comment]
It seems the issue can be closed. Please, reopen if I'm missing something.
