### ISSUE TITLE
CUDA CL_INVALID_VALUE error when instantiating a global scope queue

### ISSUE THREAD

**Issue by pvelesko** [intel/llvm#1352]
Hi all, 
the program compiles but fails at runtime when trying to create a queue that's declared global. 
```
export SYCL_BE=PI_CUDA
make cudasycl
```
[Reproducer](https://www.dropbox.com/s/l7c1cvcznwvpzwj/global_queue_codeplay.tar?dl=0).

In the comments there is a working version - everything local. Compiles and runs without crashing.

**Comment by romanovvlad** [comment]
@pvelesko  Could you please provide more details of how it fails?( Message, exception, backtrace where exception is thrown)

**Comment by pvelesko** [comment]
```
[pvelesko@dgx2 template]$ export SYCL_BE=PI_CUDA
[pvelesko@dgx2 template]$ export SYCL_DEVICE=CUDA
[pvelesko@dgx2 template]$ ./cudasycl
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -30 (CL_INVALID_VALUE) -30 (CL_INVALID_VALUE)
Aborted
[pvelesko@dgx2 template]$
```

**Comment by romanovvlad** [comment]
Could you please attach logs when PI_TRACE var is enabled? Or backtrace for the place where exception is thrown?

Does it work without setting SYCL_BE to PI_CUDA ?

**Comment by pvelesko** [comment]
One other thing I noticed this is using CUDA 10.0 instead of CUDA 10.1 
I tried switching versions but I think the person who compiled it built it against 10.0 since once I switch it can no longer find the plugin. 

Looking at the backtrace it seems like fails when
`queue q;` which gets initialized later on in an `init()` function. 
This same exact setup works with dpcpp.

> Does it work without setting SYCL_BE to PI_CUDA ?

no change

> Could you please attach logs when SYCL_PI_TRACE
```
---> piPlatformsGet(
       <unknown> : 0
       <unknown> : 0
       <unknown> : 0x7fff16d8806c
) --->        pi_result : PI_SUCCESS
---> piPlatformsGet(
       <unknown> : 1
       <unknown> : 0x80f930
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDevicesGet(
       pi_platform : 0x885450
       <unknown> : 4294967295
       <unknown> : 0
       <unknown> : 0
       <unknown> : 0x7fff16d87f4c
) --->        pi_result : PI_SUCCESS
---> piDevicesGet(
       pi_platform : 0x885450
       <unknown> : 4294967295
       <unknown> : 8
       <unknown> : 0x811170
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885550
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x811218
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885550
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8855e0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x811298
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8855e0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885670
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x811318
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885670
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885700
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8113e8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885700
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885790
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x811468
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885790
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885820
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x811578
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885820
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8858b0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8115f8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8858b0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885940
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x811678
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885940
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piPlatformsGet(
       <unknown> : 0
       <unknown> : 0
       <unknown> : 0x7fff16d8806c
) --->        pi_result : PI_SUCCESS
---> piPlatformsGet(
       <unknown> : 1
       <unknown> : 0x8e9af0
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDevicesGet(
       pi_platform : 0x2ad295e8cdd0
       <unknown> : 4294967295
       <unknown> : 0
       <unknown> : 0
       <unknown> : 0x7fff16d87f4c
) --->        pi_result : PI_SUCCESS
---> piDevicesGet(
       pi_platform : 0x2ad295e8cdd0
       <unknown> : 4294967295
       <unknown> : 8
       <unknown> : 0x8e9e10
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e99f0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8e9eb8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e99f0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a10
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8e9f58
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a10
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a30
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8e9fd8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a30
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a50
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea0a8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a50
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a70
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea128
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a70
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a90
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea238
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a90
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9ab0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea2b8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9ab0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9ad0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea338
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9ad0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87e30
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDevicesGet(
       pi_platform : 0x885450
       <unknown> : 4294967295
       <unknown> : 0
       <unknown> : 0
       <unknown> : 0x7fff16d8806c
) --->        pi_result : PI_SUCCESS
---> piDevicesGet(
       pi_platform : 0x885450
       <unknown> : 4294967295
       <unknown> : 8
       <unknown> : 0x8ea000
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885550
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea2b8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885550
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8855e0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea238
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8855e0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885670
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea128
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885670
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885700
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea0a8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885700
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885790
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8e9fd8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885790
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885820
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8e9f58
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885820
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8858b0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8e9eb8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8858b0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885940
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8ea1b8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x885940
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDevicesGet(
       pi_platform : 0x2ad295e8cdd0
       <unknown> : 4294967295
       <unknown> : 0
       <unknown> : 0
       <unknown> : 0x7fff16d8806c
) --->        pi_result : PI_SUCCESS
---> piDevicesGet(
       pi_platform : 0x2ad295e8cdd0
       <unknown> : 4294967295
       <unknown> : 8
       <unknown> : 0x8ea000
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e99f0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x8106e8
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e99f0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a10
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x810808
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a10
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a30
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x810888
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a30
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a50
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x810908
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a50
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a70
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x810988
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a70
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a90
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x810a98
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9a90
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9ab0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x810b18
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9ab0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9ad0
       <unknown> : 4096
       <unknown> : 8
       <unknown> : 0x810b98
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piDeviceGetInfo(
       <unknown> : 0x8e9ad0
       <unknown> : 4162
       <unknown> : 8
       <unknown> : 0x7fff16d87f50
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piPlatformGetInfo(
       pi_platform : 0x885450
       <unknown> : 2306
       <unknown> : 0
       <unknown> : 0
       <unknown> : 0x7fff16d87e10
) --->        pi_result : PI_SUCCESS
---> piPlatformGetInfo(
       pi_platform : 0x885450
       <unknown> : 2306
       <unknown> : 12
       <unknown> : 
       <unknown> : 0
) --->        pi_result : PI_SUCCESS
---> piContextCreate(
       <unknown> : 0x7fff16d87ef0
       <unknown> : 1
       <unknown> : 0x8109c0
       <unknown> : 0
       <unknown> : 0
       <unknown> : 0x810828
) --->        pi_result : -30
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -30 (CL_INVALID_VALUE) -30 (CL_INVALID_VALUE)

```
> backtrace for the place where exception is thrown
```
─
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 nvidia-driver-latest-dkms-cuda-libs-440.33.01-1.el7.x86_64
(gdb) bt
#0  0x00002aaaaba82377 in raise () from /lib64/libc.so.6
#1  0x00002aaaaba83a68 in abort () from /lib64/libc.so.6
#2  0x00002aaaaad5af33 in __gnu_cxx::__verbose_terminate_handler ()
    at /soft/packaging/spack/var/spack/stage/gcc-8.2.0-oaj76hylixry3xrma556tz63z6wh2iqn/gcc-8.2.0/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00002aaaaad61096 in __cxxabiv1::__terminate(void (*)()) ()
    at /soft/packaging/spack/var/spack/stage/gcc-8.2.0-oaj76hylixry3xrma556tz63z6wh2iqn/gcc-8.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00002aaaaad610d1 in std::terminate () at /soft/packaging/spack/var/spack/stage/gcc-8.2.0-oaj76hylixry3xrma556tz63z6wh2iqn/gcc-8.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00002aaaaad61304 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x411d00 <typeinfo for cl::sycl::runtime_error>, dest=0x2aaaab72b710 <cl::sycl::runtime_error::~runtime_error()>)
    at /soft/packaging/spack/var/spack/stage/gcc-8.2.0-oaj76hylixry3xrma556tz63z6wh2iqn/gcc-8.2.0/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00002aaaab5e03c0 in cl::sycl::detail::context_impl::context_impl(std::vector<cl::sycl::device, std::allocator<cl::sycl::device> >, std::function<void (cl::sycl::exception_list)>, bool) [clone .cold.214] () from /soft/compilers/llvm-intel-sycl/20200318/lib/libsycl.so
#7  0x00002aaaab7c6ff4 in cl::sycl::context::context(std::vector<cl::sycl::device, std::allocator<cl::sycl::device> > const&, std::function<void (cl::sycl::exception_list)>, bool) ()
   from /soft/compilers/llvm-intel-sycl/20200318/lib/libsycl.so
#8  0x00002aaaab7c7bb4 in cl::sycl::context::context(cl::sycl::device const&, std::function<void (cl::sycl::exception_list)>, bool) () from /soft/compilers/llvm-intel-sycl/20200318/lib/libsycl.so
#9  0x00002aaaab7e7872 in cl::sycl::queue::queue(cl::sycl::device const&, std::function<void (cl::sycl::exception_list)> const&, cl::sycl::property_list const&) ()
   from /soft/compilers/llvm-intel-sycl/20200318/lib/libsycl.so
#10 0x0000000000406309 in cl::sycl::queue::queue(cl::sycl::device_selector const&, std::function<void (cl::sycl::exception_list)> const&, cl::sycl::property_list const&) (this=0x6246d8 <q>,
    DeviceSelector=..., AsyncHandler=..., PropList=...) at /soft/compilers/llvm-intel-sycl/20200318/include/sycl/CL/sycl/queue.hpp:67
#11 0x0000000000404f05 in cl::sycl::queue::queue(cl::sycl::property_list const&) (this=0x6246d8 <q>, PropList=...) at /soft/compilers/llvm-intel-sycl/20200318/include/sycl/CL/sycl/queue.hpp:40
#12 0x00000000004037f9 in __cxx_global_var_init.1 () at ./Util.hpp:3
#13 0x000000000040392e in _GLOBAL__sub_I_main.cpp ()
#14 0x00000000004110ed in __libc_csu_init ()
#15 0x00002aaaaba6e4d5 in __libc_start_main () from /lib64/libc.so.6
#16 0x0000000000403986 in _start ()

```
