### ISSUE TITLE
[SYCL] Seg fault using simple float4 buffer

### ISSUE THREAD

**Issue by pkeir** [intel/llvm#194]
The program below gives an unexpected segmentation fault when run on 64-bit Ubuntu 19.04. I compile it with `clang++ -std=c++11 -fsycl -lOpenCL float4-intel.cpp`.

```
#include <CL/sycl.hpp>
  
namespace k { struct a; }

int main(int argc, char *argv[])
{
  using namespace cl::sycl;

  const unsigned sz{16};
  float4 v[sz];
  const range<1> r{sz};
  queue q;

  buffer<float4,1> buf(v,sz);

  q.submit([&](handler &cgh) {
    auto acc = buf.get_access<access::mode::read_write>(cgh);
    cgh.parallel_for<k::a>(r, [=](const item<1> ix) {
      acc[ix] = acc[ix];
    });
  });

  return 0;
}
```

**Comment by keryell** [comment]
Perhaps the implementation forgot that a buffer destruction is blocking when some memory has to be copied back to the host, as stated in section 3.6.9 of the specification.

**Comment by pkeir** [comment]
It produces the same seg fault if I surround the buffer declaration and submit method call with a compound statement.

**Comment by romanovvlad** [comment]
@pkeir  I cannot reproduce on latest sources. Could you please provide backtrace?

**Comment by pkeir** [comment]
Here you go. I built sycl yesterday, but perhaps my OpenCL driver needs an update.

```
(gdb) run
Starting program: /home/pkeir/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff601d700 (LWP 5204)]

Thread 1 "a.out" received signal SIGSEGV, Segmentation fault.
0x00007ffeee2b7d63 in ?? () from /usr/lib/libigc.so
(gdb) backtrace
#0  0x00007ffeee2b7d63 in ?? () from /usr/lib/libigc.so
#1  0x00007ffeee2bc47f in ?? () from /usr/lib/libigc.so
#2  0x00007ffeee1ff96e in ?? () from /usr/lib/libigc.so
#3  0x00007ffeee007678 in ?? () from /usr/lib/libigc.so
#4  0x00007ffeee1705f7 in ?? () from /usr/lib/libigc.so
#5  0x00007ffeee1712ed in ?? () from /usr/lib/libigc.so
#6  0x00007ffeee9e02f3 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
   from /usr/lib/libigc.so
#7  0x00007ffeedfd4558 in ?? () from /usr/lib/libigc.so
#8  0x00007ffeedfab555 in ?? () from /usr/lib/libigc.so
#9  0x00007ffeedea443c in ?? () from /usr/lib/libigc.so
#10 0x00007ffeedf53c2f in ?? () from /usr/lib/libigc.so
#11 0x00007ffff62f1cf7 in ?? () from /usr/local/lib/libigdrcl.so
#12 0x00007ffff62b4c71 in ?? () from /usr/local/lib/libigdrcl.so
#13 0x00007ffff6298303 in ?? () from /usr/local/lib/libigdrcl.so
#14 0x00007ffff77b6e68 in cl::sycl::detail::ProgramManager::build(_cl_program*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<_cl_device_id*, std::allocator<_cl_device_id*> >) ()
   from /home/pkeir/code/ext/intel_sycl/build/lib/libsycl.so
#15 0x00007ffff77bb8aa in cl::sycl::detail::ProgramManager::getBuiltOpenCLProgram(void*, cl::sycl::context const&) ()
   from /home/pkeir/code/ext/intel_sycl/build/lib/libsycl.so
#16 0x00007ffff77bcb9f in cl::sycl::detail::ProgramManager::getOrCreateKernel(void*, cl::sycl::context const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /home/pkeir/code/ext/intel_sycl/build/lib/libsycl.so
#17 0x00007ffff77c77bc in cl::sycl::detail::ExecCGCommand::enqueueImp() ()
   from /home/pkeir/code/ext/intel_sycl/build/lib/libsycl.so
#18 0x00007ffff77bfba5 in cl::sycl::detail::Command::enqueue() ()
   from /home/pkeir/code/ext/intel_sycl/build/lib/libsycl.so
#19 0x00007ffff77d279f in cl::sycl::detail::Scheduler::GraphProcessor::enqueueCommand(cl::sycl::detail::Command*) ()
   from /home/pkeir/code/ext/intel_sycl/build/lib/libsycl.so
#20 0x00007ffff77dded8 in cl::sycl::detail::Scheduler::addCG(std::unique_ptr<cl::sycl::detail::CG, std::default_delete<cl::sycl::detail::CG> >, std::shared_ptr<cl::sycl::detail::queue_impl>) ()
   from /home/pkeir/code/ext/intel_sycl/build/lib/libsycl.so
#21 0x0000000000409556 in cl::sycl::handler::finalize (this=0x7fffffffd4f0)
    at /home/pkeir/code/ext/intel_sycl/build/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:390
#22 0x0000000000403c8d in cl::sycl::detail::queue_impl::submit_impl<main::$_0>
    (this=0x49c850, cgf=..., self=...)
    at /home/pkeir/code/ext/intel_sycl/build/lib/clang/9.0.0/include/CL/sycl/detail/queue_impl.hpp:199
#23 0x0000000000403aa8 in cl::sycl::detail::queue_impl::submit<main::$_0> (
    this=0x49c850, cgf=..., self=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<cl::sycl::detail::queue_impl, std::allocator<cl::sycl::detail::queue_impl>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<cl::sycl::detail::queue_impl, std::allocator<cl::sycl::detail::queue_impl>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<class cl::sycl::detail::queue_impl> (use count 5, weak count 0) = {...})
    at /home/pkeir/code/ext/intel_sycl/build/lib/clang/9.0.0/include/CL/sycl/detail/queue_impl.hpp:95
#24 0x000000000040389b in cl::sycl::queue::submit<main::$_0> (
    this=0x7fffffffd8f8, cgf=...)
    at /home/pkeir/code/ext/intel_sycl/build/lib/clang/9.0.0/include/CL/sycl/queue.hpp:86
#25 0x00000000004037aa in main (argc=1, argv=0x7fffffffdb18)
    at float4-intel.cpp:16
```

**Comment by romanovvlad** [comment]
It seems the crash happens inside OCL GPU. What version of OCL GPU implementation do you use? Could you try using the latest stable version? You can download it from here: https://github.com/intel/compute-runtime/releases

**Comment by pkeir** [comment]
I was on 18.47.11882. I upgraded to 19.22.13062 and the problem is gone. Thanks.
