### ISSUE TITLE
[SYCL][OpenCL] No available targets are compatible with triple "aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by jeffhammond** [intel/llvm#2313]
I hacked around #2304 with https://github.com/jeffhammond/intel-llvm/tree/jrhammon-syclrt-platform_util-fixes but I now see the following build error.  This does not appear to be a source code issue, but a build system one, and I'm not very good at CMake.

```
error: unable to create target: 'No available targets are compatible with triple "aarch64-unknown-linux-gnu"'
```

# Details
```
ubuntu@ubuntu:~/ISYCL/build$ time python3 ../llvm/buildbot/compile.py -j2
args:Namespace(base_branch=None, branch=None, build_number=None, build_parallelism='2', builder_dir=None, obj_dir=None, pr_number=None, src_dir=None)
[Cmake Command]: cmake --build /home/ubuntu/ISYCL/llvm/build -- deploy-sycl-toolchain deploy-opencl-aot -j 2
[2/74] Performing update step for 'ocl-headers'
-- ocl-headers update command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/ocl-headers-prefix/src/ocl-headers-stamp/ocl-headers-update-*.log
[3/74] Performing update step for 'opencl-headers'
HEAD is up to date.
[6/74] Performing build step for 'ocl-headers'
-- ocl-headers build command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/ocl-headers-prefix/src/ocl-headers-stamp/ocl-headers-build-*.log
[12/74] Performing update step for 'level-zero-loader'
-- level-zero-loader update command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-update-*.log
[13/74] Performing configure step for 'level-zero-loader'
-- level-zero-loader configure command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-configure-*.log
[14/74] Performing build step for 'level-zero-loader'
-- level-zero-loader build command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-build-*.log
[15/73] Performing update step for 'ocl-icd'
-- ocl-icd update command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/ocl-icd-prefix/src/ocl-icd-stamp/ocl-icd-update-*.log
[16/73] Performing install step for 'level-zero-loader'
-- level-zero-loader install command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-install-*.log
[17/73] Performing configure step for 'ocl-icd'
-- ocl-icd configure command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/ocl-icd-prefix/src/ocl-icd-stamp/ocl-icd-configure-*.log
[20/73] Performing build step for 'ocl-icd'
-- ocl-icd build command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/ocl-icd-prefix/src/ocl-icd-stamp/ocl-icd-build-*.log
[21/72] Performing install step for 'ocl-icd'
-- ocl-icd install command succeeded.  See also /home/ubuntu/ISYCL/llvm/build/tools/sycl/ocl-icd-prefix/src/ocl-icd-stamp/ocl-icd-install-*.log
[24/72] Performing update step for 'opencl-icd'
HEAD is up to date.
[25/72] Performing configure step for 'opencl-icd'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/ISYCL/llvm/build/tools/opencl-aot/icd_build
[26/72] Generating ../../lib/libsycl-fallback-cassert.o
FAILED: lib/libsycl-fallback-cassert.o 
cd /home/ubuntu/ISYCL/llvm/build/tools/libdevice && /home/ubuntu/ISYCL/llvm/build/bin/clang-12 -fsycl -c -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 -fsycl-targets=spir64_x86_64-unknown-unknown-sycldevice,spir64_gen-unknown-unknown-sycldevice,spir64_fpga-unknown-unknown-sycldevice,spir64-unknown-unknown-sycldevice /home/ubuntu/ISYCL/llvm/libdevice/fallback-cassert.cpp -o /home/ubuntu/ISYCL/llvm/build/lib/libsycl-fallback-cassert.o
error: unable to create target: 'No available targets are compatible with triple "aarch64-unknown-linux-gnu"'
1 error generated.
[27/72] Performing build step for 'opencl-icd'
ninja: no work to do.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "../llvm/buildbot/compile.py", line 67, in <module>
    ret = main()
  File "../llvm/buildbot/compile.py", line 63, in main
    return do_compile(args)
  File "../llvm/buildbot/compile.py", line 40, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/ubuntu/ISYCL/llvm/build', '--', 'deploy-sycl-toolchain', 'deploy-opencl-aot', '-j', '2']' returned non-zero exit status 1.

real	0m6.296s
user	0m4.448s
sys	0m3.021s
```

**Comment by jbrodman** [comment]
Relevant to https://github.com/intel/llvm/issues/4 and https://github.com/intel/llvm/issues/5
