### ISSUE TITLE
[SYCL][docs] sycl/CONTRIBUTING.md gives wrong instructions on testing

### ISSUE THREAD

**Issue by jeffhammond** [intel/llvm#2317]
Line 42 of https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md says that `python buildbot/check.py -t test-sycl` is a necessary step for contribution and yet it fails on `ninja: error: unknown target 'test-sycl'`.

```
$ python3 buildbot/check.py -t test-sycl
args:Namespace(base_branch=None, branch=None, build_number=None, builder_dir=None, obj_dir=None, pr_number=None, src_dir=None, test_suite='test-sycl')
[Cmake Command]: cmake --build /localdisk/jrhammon/llvm/build -- test-sycl -j 224
ninja: error: unknown target 'test-sycl'
Traceback (most recent call last):
  File "buildbot/check.py", line 64, in <module>
    ret = main()
  File "buildbot/check.py", line 61, in main
    return do_check(args)
  File "buildbot/check.py", line 38, in do_check
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir, env=env_tmp)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/localdisk/jrhammon/llvm/build', '--', 'test-sycl', '-j', '224']' returned non-zero exit status 1.
```

If I remove the test argument, I can run the full suite, or I can run the SYCL subset like this:
```
jrhammon@ortce-cavium3:/localdisk/jrhammon/llvm$ python3 buildbot/check.py -t sycl
args:Namespace(base_branch=None, branch=None, build_number=None, builder_dir=None, obj_dir=None, pr_number=None, src_dir=None, test_suite='sycl')
[Cmake Command]: cmake --build /localdisk/jrhammon/llvm/build -- sycl -j 224
[2/16] Performing update step for 'ocl-headers'
-- ocl-headers update command succeeded.  See also /localdisk/jrhammon/llvm/build/tools/sycl/ocl-headers-prefix/src/ocl-headers-stamp/ocl-headers-update-*.log
[5/16] Performing build step for 'ocl-headers'
-- ocl-headers build command succeeded.  See also /localdisk/jrhammon/llvm/build/tools/sycl/ocl-headers-prefix/src/ocl-headers-stamp/ocl-headers-build-*.log
[8/16] Performing update step for 'ocl-icd'
-- ocl-icd update command succeeded.  See also /localdisk/jrhammon/llvm/build/tools/sycl/ocl-icd-prefix/src/ocl-icd-stamp/ocl-icd-update-*.log
[10/16] Performing configure step for 'ocl-icd'
-- ocl-icd configure command succeeded.  See also /localdisk/jrhammon/llvm/build/tools/sycl/ocl-icd-prefix/src/ocl-icd-stamp/ocl-icd-configure-*.log
[11/16] Performing build step for 'ocl-icd'
-- ocl-icd build command succeeded.  See also /localdisk/jrhammon/llvm/build/tools/sycl/ocl-icd-prefix/src/ocl-icd-stamp/ocl-icd-build-*.log
[12/16] Performing install step for 'ocl-icd'
-- ocl-icd install command succeeded.  See also /localdisk/jrhammon/llvm/build/tools/sycl/ocl-icd-prefix/src/ocl-icd-stamp/ocl-icd-install-*.log
[16/16] Creating library symlink lib/libsycl.so.3 lib/libsycl.so
```

**Comment by bader** [comment]
@jeffhammond, #2319 should address this issue.
NOTE: `check.py -t <target>` just builds the target. Test target names start with `check-` prefix. 
`python3 buildbot/check.py -t sycl` - builds `sycl` target, which builds only SYCL library, but doesn't validate it.
Please, use `python3 buildbot/check.py -t check-sycl` to the the library or use this script w/o arguments to validate the whole toolchain.
