### ISSUE TITLE
[SYCL][MacOS] invalid section name '__CLANG_OFFLOAD_BUNDLE__sycl-spir64_x86_64-unknown-unknown-sycldevice'

### ISSUE THREAD

**Issue by jeffhammond** [intel/llvm#2360]
I have no idea where to start with this one.

# Hard problem
```
jrhammon-mac02:libdevice jrhammon$ /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-12 -fsycl -c -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 -fsycl-targets=spir64_x86_64-unknown-unknown-sycldevice,spir64_gen-unknown-unknown-sycldevice,spir64_fpga-unknown-unknown-sycldevice,spir64-unknown-unknown-sycldevice /Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/glibc_wrapper.cpp -o /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/libsycl-glibc.o
llvm-objcopy: error: '/var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-09d819.o': invalid section name '__CLANG_OFFLOAD_BUNDLE__sycl-spir64_x86_64-unknown-unknown-sycldevice' (should be formatted as '<segment name>,<section name>')
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-offload-bundler: error: 'llvm-objcopy' tool failed
clang-12: error: clang-offload-bundler command failed with exit code 1 (use -v to see invocation)
```

# Details
```
jrhammon-mac02:libdevice jrhammon$ /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-12 -fsycl -c -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 -fsycl-targets=spir64_x86_64-unknown-unknown-sycldevice,spir64-unknown-unknown-sycldevice /Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/glibc_wrapper.cpp -o /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/libsycl-glibc.o -v
clang version 12.0.0 (https://github.com/intel/llvm.git 6e9bf3b5419360fc1bb09afbed219db70fb24415)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin
 "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-12" -cc1 -triple spir64_x86_64-unknown-unknown-sycldevice -fsycl -fsycl-is-device -fdeclare-spirv-builtins -mllvm -sycl-opt -aux-triple x86_64-apple-darwin18.7.0 -sycl-std=2017 -fsycl-std-layout-kernel-params -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-llvm-bc -emit-llvm-uselists -disable-free -main-file-name glibc_wrapper.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -fno-verbose-asm -mconstructor-aliases -aux-target-cpu penryn -target-sdk-version=10.15 -fcompatibility-qualified-id-block-type-checking -fno-split-dwarf-inlining -debugger-tuning=gdb -target-linker-version 530 -v -resource-dir /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0 -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/sycl -I/usr/local/Cellar/llvm/10.0.0_3/include/c++/v1 -I/usr/local/Cellar/llvm/10.0.0_3/include -I/usr/local/Cellar/llvm/10.0.0_3/include/c++ -I/opt/intel/compilers_and_libraries_2020.2.258/mac/mkl/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/stdlib -I/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /usr/include/c++/v1 -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /usr/include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /usr/include -Wno-sycl-strict -Wno-undefined-internal -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/tools/libdevice -ferror-limit 19 -sycl-std=2017 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -o /var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-f7bb65.bc -x c++ /Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/glibc_wrapper.cpp
clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-apple-darwin18.7.0
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/usr/include"
ignoring nonexistent directory "/usr/include"
ignoring nonexistent directory "/usr/include"
ignoring duplicate directory "/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/Cellar/llvm/10.0.0_3/include/c++/v1
 /usr/local/Cellar/llvm/10.0.0_3/include
 /usr/local/Cellar/llvm/10.0.0_3/include/c++
 /opt/intel/compilers_and_libraries_2020.2.258/mac/mkl/include
 /opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/include
 /opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/stdlib
 /opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include
 /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/sycl
 /usr/local/include
 /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include
End of search list.
 "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-12" -cc1 -triple spir64-unknown-unknown-sycldevice -fsycl -fsycl-is-device -fdeclare-spirv-builtins -mllvm -sycl-opt -aux-triple x86_64-apple-darwin18.7.0 -sycl-std=2017 -fsycl-std-layout-kernel-params -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-llvm-bc -emit-llvm-uselists -disable-free -main-file-name glibc_wrapper.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -fno-verbose-asm -mconstructor-aliases -aux-target-cpu penryn -target-sdk-version=10.15 -fcompatibility-qualified-id-block-type-checking -fno-split-dwarf-inlining -debugger-tuning=gdb -target-linker-version 530 -v -resource-dir /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0 -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/sycl -I/usr/local/Cellar/llvm/10.0.0_3/include/c++/v1 -I/usr/local/Cellar/llvm/10.0.0_3/include -I/usr/local/Cellar/llvm/10.0.0_3/include/c++ -I/opt/intel/compilers_and_libraries_2020.2.258/mac/mkl/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/stdlib -I/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /usr/include/c++/v1 -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /usr/include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /usr/include -Wno-sycl-strict -Wno-undefined-internal -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/tools/libdevice -ferror-limit 19 -sycl-std=2017 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -o /var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-9aba63.bc -x c++ /Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/glibc_wrapper.cpp
clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-apple-darwin18.7.0
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/usr/include"
ignoring nonexistent directory "/usr/include"
ignoring nonexistent directory "/usr/include"
ignoring duplicate directory "/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/Cellar/llvm/10.0.0_3/include/c++/v1
 /usr/local/Cellar/llvm/10.0.0_3/include
 /usr/local/Cellar/llvm/10.0.0_3/include/c++
 /opt/intel/compilers_and_libraries_2020.2.258/mac/mkl/include
 /opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/include
 /opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/stdlib
 /opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include
 /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/sycl
 /usr/local/include
 /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include
End of search list.
 "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-12" -cc1 -triple spir64_x86_64-unknown-unknown-sycldevice -fsycl -fsycl-is-device -fdeclare-spirv-builtins -mllvm -sycl-opt -aux-triple x86_64-apple-darwin18.7.0 -sycl-std=2017 -fsycl-std-layout-kernel-params -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -fsyntax-only -disable-free -main-file-name glibc_wrapper.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -fno-verbose-asm -mconstructor-aliases -aux-target-cpu penryn -target-sdk-version=10.15 -fcompatibility-qualified-id-block-type-checking -fno-split-dwarf-inlining -debugger-tuning=gdb -target-linker-version 530 -v -resource-dir /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0 -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/sycl -I/usr/local/Cellar/llvm/10.0.0_3/include/c++/v1 -I/usr/local/Cellar/llvm/10.0.0_3/include -I/usr/local/Cellar/llvm/10.0.0_3/include/c++ -I/opt/intel/compilers_and_libraries_2020.2.258/mac/mkl/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/stdlib -I/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /usr/include/c++/v1 -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /usr/include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /usr/include -Wno-sycl-strict -Wno-undefined-internal -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/tools/libdevice -ferror-limit 19 -sycl-std=2017 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -fsycl-int-header=/var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-1f128f.h -faddrsig -o /var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-1f128f.h -x c++ /Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/glibc_wrapper.cpp
clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-apple-darwin18.7.0
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/usr/include"
ignoring nonexistent directory "/usr/include"
ignoring nonexistent directory "/usr/include"
ignoring duplicate directory "/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/Cellar/llvm/10.0.0_3/include/c++/v1
 /usr/local/Cellar/llvm/10.0.0_3/include
 /usr/local/Cellar/llvm/10.0.0_3/include/c++
 /opt/intel/compilers_and_libraries_2020.2.258/mac/mkl/include
 /opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/include
 /opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/stdlib
 /opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include
 /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/sycl
 /usr/local/include
 /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include
End of search list.
 "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-12" -cc1 -triple x86_64-apple-macosx10.14.0 -sycl-std=2017 -fsycl-std-layout-kernel-params -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name glibc_wrapper.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-rounding-math -munwind-tables -target-sdk-version=10.15 -fcompatibility-qualified-id-block-type-checking -target-cpu penryn -debugger-tuning=lldb -target-linker-version 530 -v -resource-dir /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0 -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/sycl -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I/usr/local/Cellar/llvm/10.0.0_3/include/c++/v1 -I/usr/local/Cellar/llvm/10.0.0_3/include -I/usr/local/Cellar/llvm/10.0.0_3/include/c++ -I/opt/intel/compilers_and_libraries_2020.2.258/mac/mkl/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/stdlib -I/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include -I/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include -stdlib=libc++ -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1 -stdlib=libc++ -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1 -stdlib=libc++ -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -Wno-sycl-strict -Wno-undefined-internal -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/tools/libdevice -ferror-limit 19 -stack-protector 1 -sycl-std=2017 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fcolor-diagnostics -include /var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-1f128f.h -dependency-filter /var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-1f128f.h -fsycl -fsycl-is-host -o /var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-d5f27c.o -x c++ /Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/glibc_wrapper.cpp
clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-apple-darwin18.7.0
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/Library/Frameworks"
ignoring duplicate directory "/opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include"
ignoring duplicate directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include"
ignoring duplicate directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
ignoring duplicate directory "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include"
ignoring duplicate directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/Cellar/llvm/10.0.0_3/include/c++/v1
 /usr/local/Cellar/llvm/10.0.0_3/include
 /usr/local/Cellar/llvm/10.0.0_3/include/c++
 /opt/intel/compilers_and_libraries_2020.2.258/mac/mkl/include
 /opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/include
 /opt/intel/compilers_and_libraries_2020.2.258/mac/pstl/stdlib
 /opt/intel/compilers_and_libraries_2020.2.258/mac/tbb/include
 /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/../include/sycl
 /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/clang/12.0.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-offload-bundler" -type=o -targets=sycl-spir64_x86_64-unknown-unknown-sycldevice,sycl-spir64-unknown-unknown-sycldevice,host-x86_64-apple-darwin18.7.0 -outputs=/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/libsycl-glibc.o -inputs=/var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-f7bb65.bc,/var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-9aba63.bc,/var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-d5f27c.o
llvm-objcopy: error: '/var/folders/_m/t82y07c551791vcmm8c6l7mh0000gq/T/glibc_wrapper-d5f27c.o': invalid section name '__CLANG_OFFLOAD_BUNDLE__sycl-spir64_x86_64-unknown-unknown-sycldevice' (should be formatted as '<segment name>,<section name>')
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-offload-bundler: error: 'llvm-objcopy' tool failed
clang-12: error: clang-offload-bundler command failed with exit code 1 (use -v to see invocation)
```

To get to this point, I had to solve the following.

# Easy problem
```
jrhammon-mac02:llvm jrhammon$ python3 ./buildbot/compile.py -j1
args:Namespace(base_branch=None, branch=None, build_number=None, build_parallelism='1', builder_dir=None, obj_dir=None, pr_number=None, src_dir=None)
[Cmake Command]: cmake --build /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build -- deploy-sycl-toolchain deploy-opencl-aot -j 1
[1/80] Generating ../../lib/libsycl-glibc.o
FAILED: lib/libsycl-glibc.o 
cd /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/tools/libdevice && /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/bin/clang-12 -fsycl -c -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 -fsycl-targets=spir64_x86_64-unknown-unknown-sycldevice,spir64_gen-unknown-unknown-sycldevice,spir64_fpga-unknown-unknown-sycldevice,spir64-unknown-unknown-sycldevice /Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/glibc_wrapper.cpp -o /Users/jrhammon/Work/OpenCL/ISYCL/llvm/build/lib/libsycl-glibc.o
In file included from /Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/glibc_wrapper.cpp:9:
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/libdevice/wrapper.h:16:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./buildbot/compile.py", line 67, in <module>
    ret = main()
  File "./buildbot/compile.py", line 63, in main
    return do_compile(args)
  File "./buildbot/compile.py", line 40, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/Users/jrhammon/Work/OpenCL/ISYCL/llvm/build', '--', 'deploy-sycl-toolchain', 'deploy-opencl-aot', '-j', '1']' returned non-zero exit status 1.
```

# Fixing `cstddef` issue
```
jrhammon-mac02:libdevice jrhammon$ export CPATH=/usr/local/Cellar/llvm/10.0.0_3/include:/usr/local/Cellar/llvm/10.0.0_3/include/c++:/usr/local/Cellar/llvm/10.0.0_3/include/c++/v1:$CPATH
```

**Comment by alexbatashev** [comment]
@jeffhammond the error comes from here:
https://github.com/intel/llvm/blob/f257378163a4b71503a12ec6c065a22a15a04a39/llvm/tools/llvm-objcopy/MachO/MachOObjcopy.cpp#L347

When I was experimenting with macOS, I just renamed that section to (if I remember correctly) `__TEXT,<OTHER_STUFF>` somewhere around here:
https://github.com/intel/llvm/blob/f257378163a4b71503a12ec6c065a22a15a04a39/clang/tools/clang-offload-bundler/ClangOffloadBundler.cpp#L112

And it sort of worked. However, I doubt it is a proper way to solve the issue.

**Comment by jeffhammond** [comment]
@alexbatashev Thanks!  At this point, I am only trying to get the host device working, so perhaps hacking around this is okay for now.

**Comment by alexbatashev** [comment]
@jeffhammond if you only need host device, you can simply pass `-lsycl -I<path/to/sycl/headers>`. You can do so with any C++ compiler, and it will work. This won't allow you to run lit tests, though, as they now use `%clangxx` placeholder, and each test contains `-fsycl` flag.

**Comment by jeffhammond** [comment]
The error above is extracted from the DPC++ build.  I am trying to get DPC++ to build without error.  I am not sure how to apply your method in that context.

**Comment by alexbatashev** [comment]
Alright, I see. There's now a target, called `libdevice`, which uses compiled `clang++` to produce some SPIR-V images, which are then linked dynamically to provide some C99 functionality in SYCL. I think, you can just disable this project in configure.py. There's also examples target and some SYCL RT tests, that use the same technique. You probably need to disable those in CMakeLists.txt:
https://github.com/intel/llvm/blob/2f64227a0405e6d4eacdf0974fb8e64462d01a8d/sycl/CMakeLists.txt#L400
https://github.com/intel/llvm/blob/2f64227a0405e6d4eacdf0974fb8e64462d01a8d/sycl/unittests/CMakeLists.txt#L14
