### ISSUE TITLE
level-zero-loader-download error: pathspec 'v0.91.21' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by jeffhammond** [intel/llvm#2651]
Did somebody do a bad thing w.r.t. Level Zero?

```
[15/595] Performing download step (git clone) for 'level-zero-loader'
FAILED: tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-download 
cd /nfs/pdx/home/jrhammon/ISYCL/llvm/build/tools/sycl/plugins/level_zero/level_zero && /nfs/pdx/home/jrhammon/CMAKE/bin/cmake -P /nfs/pdx/home/jrhammon/ISYCL/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/tmp/level-zero-loader-gitclone.cmake && /nfs/pdx/home/jrhammon/CMAKE/bin/cmake -E touch /nfs/pdx/home/jrhammon/ISYCL/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/src/level-zero-loader-stamp/level-zero-loader-download
Cloning into 'level_zero_loader'...
error: pathspec 'v0.91.21' did not match any file(s) known to git.
CMake Error at /nfs/pdx/home/jrhammon/ISYCL/llvm/build/tools/sycl/plugins/level_zero/level-zero-loader-prefix/tmp/level-zero-loader-gitclone.cmake:40 (message):
  Failed to checkout tag: 'v0.91.21'


[16/595] Performing update step for 'ocl-icd'
Current branch HEAD is up to date.
[17/595] Performing update step for 'opencl-icd'
Current branch HEAD is up to date.
[21/595] Building CXX object tools/clang/tools/driver/CMakeFiles/clang.dir/cc1_main.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./buildbot/compile.py", line 63, in <module>
    ret = main()
  File "./buildbot/compile.py", line 59, in main
    return do_compile(args)
  File "./buildbot/compile.py", line 37, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/opt/intel/oneapi/intelpython/latest/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/nfs/pdx/home/jrhammon/ISYCL/llvm/build', '--', 'deploy-sycl-toolchain', 'deploy-opencl-aot', '-j', '80']' returned non-zero exit status 1.
```

**Comment by jandres742** [comment]
I dont see the v0.91.21 tag in the level-zero repo, https://github.com/oneapi-src/level-zero/tags. Seems like someone wrote the wrong tag somewhere.

```sh
$:~/level-zero-loader-github/level-zero$ git tag -l
v0.91
v0.91.10
v0.91.7
v1.0
v1.0.12
v1.0.13
````

**Comment by bader** [comment]
@jeffhammond, your code base seems to be quite old - level_zero plug-in switched to v1.0 tag 1.5 months ago.
https://github.com/intel/llvm/commit/6d34b95c3eb3bccf5d739d66a7c57eed196cc206

Please, update your code base.

**Comment by jeffhammond** [comment]
Sorry for the trouble. I guess I was switching between too many terminals and forgot to `git clean -dfx ; git reset --hard ; git pull` like usual.
