### ISSUE TITLE
[SYCL] error: unknown target ABI 'aapcs'

### ISSUE THREAD

**Issue by jeffhammond** [intel/llvm#2687]
This looks like a recent regression in the ARM build, at least it appeared when I switched from the Raspberry Pi4 Ubuntu 20.04 to Xavier AGX Ubuntu 18.04.

I know that e313d550b328379c089fc0f8f86944711dedda40 works and I'm using that.  I have not run `git bisect` yet.

```
git clean -dfx
python3 ./buildbot/configure.py --cuda --arm --cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0"
```

```
jrhammon@xavier-agx:~/ISYCL$ python3 ./buildbot/compile.py 
args:Namespace(base_branch=None, branch=None, build_number=None, build_parallelism=None, builder_dir=None, obj_dir=None, pr_number=None, src_dir=None)
[Cmake Command]: cmake --build /home/jrhammon/ISYCL/build -- deploy-sycl-toolchain deploy-opencl-aot -j 8
[2/72] Generating ../../lib/libsycl-fallback-complex-fp64.spv
FAILED: lib/libsycl-fallback-complex-fp64.spv 
cd /home/jrhammon/ISYCL/build/tools/libdevice && /home/jrhammon/ISYCL/build/bin/clang-12 -S -fsycl-device-only -fno-sycl-use-bitcode -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 /home/jrhammon/ISYCL/libdevice/fallback-complex-fp64.cpp -o /home/jrhammon/ISYCL/build/lib/libsycl-fallback-complex-fp64.spv
error: unknown target ABI 'aapcs'
[3/72] Generating ../../lib/libsycl-fallback-cmath.spv
FAILED: lib/libsycl-fallback-cmath.spv 
cd /home/jrhammon/ISYCL/build/tools/libdevice && /home/jrhammon/ISYCL/build/bin/clang-12 -S -fsycl-device-only -fno-sycl-use-bitcode -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 /home/jrhammon/ISYCL/libdevice/fallback-cmath.cpp -o /home/jrhammon/ISYCL/build/lib/libsycl-fallback-cmath.spv
error: unknown target ABI 'aapcs'
[4/72] Generating ../../lib/libsycl-fallback-cassert.spv
FAILED: lib/libsycl-fallback-cassert.spv 
cd /home/jrhammon/ISYCL/build/tools/libdevice && /home/jrhammon/ISYCL/build/bin/clang-12 -S -fsycl-device-only -fno-sycl-use-bitcode -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 /home/jrhammon/ISYCL/libdevice/fallback-cassert.cpp -o /home/jrhammon/ISYCL/build/lib/libsycl-fallback-cassert.spv
error: unknown target ABI 'aapcs'
[5/72] Generating ../../lib/libsycl-fallback-complex.spv
FAILED: lib/libsycl-fallback-complex.spv 
cd /home/jrhammon/ISYCL/build/tools/libdevice && /home/jrhammon/ISYCL/build/bin/clang-12 -S -fsycl-device-only -fno-sycl-use-bitcode -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 /home/jrhammon/ISYCL/libdevice/fallback-complex.cpp -o /home/jrhammon/ISYCL/build/lib/libsycl-fallback-complex.spv
error: unknown target ABI 'aapcs'
[6/72] Generating ../../lib/libsycl-fallback-cmath-fp64.spv
FAILED: lib/libsycl-fallback-cmath-fp64.spv 
cd /home/jrhammon/ISYCL/build/tools/libdevice && /home/jrhammon/ISYCL/build/bin/clang-12 -S -fsycl-device-only -fno-sycl-use-bitcode -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 /home/jrhammon/ISYCL/libdevice/fallback-cmath-fp64.cpp -o /home/jrhammon/ISYCL/build/lib/libsycl-fallback-cmath-fp64.spv
error: unknown target ABI 'aapcs'
[8/72] Performing update step for 'ocl-headers'
-- ocl-headers update command succeeded.  See also /home/jrhammon/ISYCL/build/tools/sycl/ocl-headers-prefix/src/ocl-headers-stamp/ocl-headers-update-*.log
[9/72] Generating ../../lib/clc/libspirv-nvptx64--.bc
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./buildbot/compile.py", line 67, in <module>
    ret = main()
  File "./buildbot/compile.py", line 63, in main
    return do_compile(args)
  File "./buildbot/compile.py", line 40, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/jrhammon/ISYCL/build', '--', 'deploy-sycl-toolchain', 'deploy-opencl-aot', '-j', '8']' returned non-zero exit status 1.

```

**Comment by bader** [comment]
Most likely this regression introduced by recent changes in the community code pulled with #2628.

**Comment by jeffhammond** [comment]
@bader I'm not sure about the `cuda` label.  This is specific to ARM, not CUDA.

**Comment by bader** [comment]
You might be right. 

I thought `libclc` part has failed to build:
> [9/72] Generating ../../lib/clc/libspirv-nvptx64--.bc
> ninja: build stopped: subcommand failed.

It it might be that only `libdevice` build failed. I'll remove `cuda` label.

**Comment by jeffhammond** [comment]
The MCVE is below:
```
jrhammon@xavier-agx:~/ISYCL$ cd /home/jrhammon/ISYCL/build/tools/libdevice && /home/jrhammon/ISYCL/build/bin/clang-12 -S -fsycl-device-only -fno-sycl-use-bitcode -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2017 /home/jrhammon/ISYCL/libdevice/fallback-cmath.cpp -o /home/jrhammon/ISYCL/build/lib/libsycl-fallback-cmath.spv
error: unknown target ABI 'aapcs'
```

**Comment by AlexeySachkov** [comment]
@jeffhammond, is this issue still actual?

**Comment by jeffhammond** [comment]
I don't know. Haven't had time to retest. Will try to do it by the end of the month.
