### ISSUE TITLE
Scheduler stuck on empty memcpy and memset

### ISSUE THREAD

**Issue by Michoumichmich** [intel/llvm#3981]
Hello, 

I've encountered a bug that involves memcpy when the copied size is 0. Turns out that you cannot make a kernel that depends on an event returned by `q.memcpy(dst, src, 0)`. Here's a little reproductible example:

```c++
#include <sycl/sycl.hpp>

using byte = uint8_t;
constexpr size_t input_block_size = 1024ul * 1024ul; //bytes

void do_work(byte* ptr, size_t i){ptr[i] = 0;}

sycl::event work_submission(sycl::queue &q, sycl::event e, byte*ptr){
    return q.submit([&](sycl::handler & cgh){
        cgh.depends_on(e);
        cgh.parallel_for(sycl::range<1>(input_block_size), [=](sycl::id<1>i ){
            do_work(ptr, i.get(0));
        });
    });
}

sycl::event submit_queue_with_dependency(sycl::queue &q, byte* host_ptr){
    auto device_ptr = sycl::malloc_device<byte>(input_block_size, q);
    auto e = q.memcpy(device_ptr, host_ptr, 0); ////// 
    return work_submission(q, e, device_ptr);
}

sycl::event submit_queue_without_dependency(sycl::queue &q, byte* host_ptr){
    auto device_ptr = sycl::malloc_device<byte>(input_block_size, q);
    q.memcpy(device_ptr, host_ptr, 0).wait(); ////// 
    return work_submission(q, sycl::event{}, device_ptr);
}


int main() {    
    auto q = sycl::queue{};

    auto host_alloc = (byte *) malloc(input_block_size * sizeof(byte));

    submit_queue_without_dependency(q, host_alloc).wait();
    std::cout << "Done without dependency" << std::endl;
    submit_queue_with_dependency(q, host_alloc).wait();
    std::cout << "Done with dependency" << std::endl; // Unreachable with clang
    
    free(host_alloc);
    return 0;
}

```

The mentioned behaviour is not limited to the `host_device`, it happens also for other devices/targets

I haven't checked whether the same issue also appears for H2H, D2H and D2D copies. If could also be happening for `memset`, `copy` and `fill`. 

Here's the bt of where it hangs:

```
0x00007ffff7141000 in cl::sycl::detail::event_impl::waitInternal() const () from /home/michel/sycl_workspace/deploy/lib/libsycl.so.5
(gdb) bt
#0  0x00007ffff7141000 in cl::sycl::detail::event_impl::waitInternal() const () from /home/michel/sycl_workspace/deploy/lib/libsycl.so.5
#1  0x00007ffff71b363c in cl::sycl::detail::ExecCGCommand::enqueueImp() () from /home/michel/sycl_workspace/deploy/lib/libsycl.so.5
#2  0x00007ffff71ac45d in cl::sycl::detail::Command::enqueue(cl::sycl::detail::EnqueueResultT&, cl::sycl::detail::BlockingT) ()
   from /home/michel/sycl_workspace/deploy/lib/libsycl.so.5
#3  0x00007ffff71bb898 in cl::sycl::detail::Scheduler::addCG(std::unique_ptr<cl::sycl::detail::CG, std::default_delete<cl::sycl::detail::CG> >, std::shared_ptr<cl::sycl::detail::queue_impl>) () from /home/michel/sycl_workspace/deploy/lib/libsycl.so.5
#4  0x00007ffff71f34ed in cl::sycl::handler::finalize() () from /home/michel/sycl_workspace/deploy/lib/libsycl.so.5
#5  0x00007ffff720ed7e in cl::sycl::detail::queue_impl::submit_impl(std::function<void (cl::sycl::handler&)> const&, std::shared_ptr<cl::sycl::detail::queue_impl> const&, cl::sycl::detail::code_location const&) () from /home/michel/sycl_workspace/deploy/lib/libsycl.so.5
#6  0x00007ffff720ee82 in cl::sycl::queue::submit_impl(std::function<void (cl::sycl::handler&)>, cl::sycl::detail::code_location const&) ()
   from /home/michel/sycl_workspace/deploy/lib/libsycl.so.5
#7  0x0000000000401fce in submit_queue_with_dependency(cl::sycl::queue&, unsigned char*) ()
#8  0x000000000040263f in main ()
```

**Comment by Michoumichmich** [comment]
Turns out memset is also affected.

**Comment by romanovvlad** [comment]
@dnmokhov Could you please confirm that this is fixed?

**Comment by dnmokhov** [comment]
This looks a little different from what was fixed in #4727. Here, we are dependent on an empty event, which should have always worked (as a no-op). Let me try to run this reproducer.

**Comment by dnmokhov** [comment]
I cannot reproduce the hang in the latest nightly:
```
$ clang++ --version
clang version 14.0.0 (https://github.com/intel/llvm.git 35ccdd5a6b3c467cd39bfb14f0abc7ef2bc20667)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ...

$ clang++ -fsycl test.cpp

$ SYCL_DEVICE_FILTER=host ./a.out
Done without dependency
Done with dependency

$ SYCL_DEVICE_FILTER=cpu ./a.out
Done without dependency
Done with dependency

$ SYCL_DEVICE_FILTER=gpu ./a.out
Done without dependency
Done with dependency
```

**Comment by Michoumichmich** [comment]
Hello @dnmokhov, I tried on my side and is seems resolved too! I remember that code definitely blocking. Thanks for looking into that though. Michel,
