### ISSUE TITLE
Building LLVM for CUDA on HPC system fails

### ISSUE THREAD

**Issue by ThielemannSe** [intel/llvm#5181]
I'm trying to build the DPC++ compiler on a RHEM based HPC-System, with slurs used as workload manager. After cloning from the official repository ( sycl branch ) I'm using the following script to build the compiler:

```bash
module load modenv/scs5
module load GCC/10.2.0
module load Ninja
module load CUDAcore/11.1.1
module load Python
module load CMake

export $DPCPP_HOME=~/sycl_workspace
export CUDA_LIB_PATH=/sw/installed/CUDAcore/11.1.1/lib64/stubs

python3 $DPCPP_HOME/llvm/buildbot/configure.py --cuda --no-werror --cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=/sw/installed/CUDAcore/11.1.1"
python3 $DPCPP_HOME/llvm/buildbot/compile.py
``` 

Every time the compilation fails with the following output:
```bash
[1595/3156] Building CXX object tools/sycl/opencl/opencl-aot/CMakeFiles/opencl-aot.dir/source/utils.cpp.o
FAILED: tools/sycl/opencl/opencl-aot/CMakeFiles/opencl-aot.dir/source/utils.cpp.o
/sw/installed/GCCcore/10.2.0/bin/c++ -DCL_TARGET_OPENCL_VERSION=220 -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/sycl/opencl/opencl-aot -I/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot -Iinclude -I/home/h0/seth295c/sycl_workspace/llvm/llvm/include -I/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/include -isystem /sw/installed/zlib/1.2.11-GCCcore-10.2.0/include -isystem _deps/ocl-headers-src -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wextra -Wno-deprecated-declarations -O3 -DNDEBUG  -fno-exceptions -fno-rtti -UNDEBUG -Wno-unused-parameter -std=c++17 -MD -MT tools/sycl/opencl/opencl-aot/CMakeFiles/opencl-aot.dir/source/utils.cpp.o -MF tools/sycl/opencl/opencl-aot/CMakeFiles/opencl-aot.dir/source/utils.cpp.o.d -o tools/sycl/opencl/opencl-aot/CMakeFiles/opencl-aot.dir/source/utils.cpp.o -c /home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp
In file included from /home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:15:
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/include/utils.h:57:60: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
   57 | std::tuple<cl_platform_id, std::string, std::string, cl_int>
      |                                                            ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/include/utils.h:66:45: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
   66 | std::tuple<cl_device_id, std::string, cl_int>
      |                                             ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/include/utils.h:74:44: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
   74 | std::tuple<std::string, std::string, cl_int>
      |                                            ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/include/utils.h:84:43: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
   84 | std::tuple<cl_program, std::string, cl_int>
      |                                           ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/include/utils.h:93:50: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
   93 | std::tuple<std::vector<char>, std::string, cl_int>
      |                                                  ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:160:60: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
  160 | std::tuple<cl_platform_id, std::string, std::string, cl_int>
      |                                                            ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:270:45: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
  270 | std::tuple<cl_device_id, std::string, cl_int>
      |                                             ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp: In function ‘std::tuple<_cl_device_id*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> getOpenCLDevice(cl_platform_id, DeviceType)’:
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:272:38: warning: ignoring attributes on template argument ‘cl_device_type’ {aka ‘long unsigned int’} [-Wignored-attributes]
  272 |   std::map<DeviceType, cl_device_type> DeviceTypesToOpenCLDeviceTypes{
      |                                      ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp: At global scope:
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:291:44: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
  291 | std::tuple<std::string, std::string, cl_int>
      |                                            ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:322:43: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
  322 | std::tuple<cl_program, std::string, cl_int>
      |                                           ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp: In function ‘std::tuple<_cl_program*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> createProgramWithIL(std::vector<char>, cl_context, cl_platform_id, cl_device_id)’:
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:337:71: warning: ignoring attributes on template argument ‘_cl_program*(cl_context, const void*, size_t, cl_int*)’ {aka ‘_cl_program*(_cl_context*, const void*, long unsigned int, int*)’} [-Wignored-attributes]
  337 |   std::function<cl_program(cl_context, const void *, size_t, cl_int *)>
      |                                                                       ^
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:347:27: error: ‘clCreateProgramWithIL’ was not declared in this scope; did you mean ‘CreateProgramWithIL’?
  347 |     CreateProgramWithIL = clCreateProgramWithIL;
      |                           ^~~~~~~~~~~~~~~~~~~~~
      |                           CreateProgramWithIL
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:362:44: error: ‘clCreateProgramWithILKHR_fn’ does not name a type; did you mean ‘CreateProgramWithIL’?
  362 |     CreateProgramWithIL = reinterpret_cast<clCreateProgramWithILKHR_fn>(
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            CreateProgramWithIL
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp: At global scope:
/home/h0/seth295c/sycl_workspace/llvm/opencl/opencl-aot/source/utils.cpp:380:50: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
  380 | std::tuple<std::vector<char>, std::string, cl_int>
      |                                                  ^
[1618/3156] Building CXX object lib/Passes/CMakeFiles/LLVMPasses.dir/PassBuilder.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./buildbot/compile.py", line 71, in <module>
    ret = main()
  File "./buildbot/compile.py", line 67, in main
    return do_compile(args)
  File "./buildbot/compile.py", line 42, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/sw/installed/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/h0/seth295c/sycl_workspace/llvm/build', '--', 'deploy-sycl-toolchain', '-j', '24']' returned non-zero exit status 1.
```

Could this be an issue with the OpenCL headers?

**Comment by alexbatashev** [comment]
@ThielemannSe it appears that the compiler has picked up NVidia's OpenCL headers, which are outdated. I'm not sure if there's a good way to deal with this, but one thing that works for sure is looking up where `cl.h` is (most likely some system-default location, like `/usr/include/CL`) and move the entire `CL` directory somewhere.

**Comment by ThielemannSe** [comment]
@alexbatashev Unfortunately, I cannot move the OpenCL headers because CUDA is loaded as a module by Slurm. 
Is there a way to set proper includes to get the compiler taking the the fetched OpenCL headers?

**Comment by zjin-lcf** [comment]
May you remove the line 'module load CUDAcore/11.1.1'  and try again ?  I assume '/sw/installed/CUDAcore/11.1.1' is always there with module load.

**Comment by ThielemannSe** [comment]
@zjin-lcf Many Thanks. With your tip, the build process now works. However, I get an error message when I try to compile the sample program.

I'm compiling with following script:
```bash
#!/bin/bash

CUDA_LIB_PATH=/sw/installed/CUDAcore/11.1.1
DPCPP_HOME=~/sycl_workspace

module load CUDAcore/11.1.1
module load GCC/10.2.0

$DPCPP_HOME/llvm/build/bin/clang++ --gcc-toolchain="$(which gcc)"  -std=c++17 -O3 -fsycl -fsycl-targets=nvptx64-nvidia-cuda --cuda-path=$CUDA_LIB_PATH example.cpp -o example
```

I get this error message:
```bash
In file included from example.cpp:1:
In file included from /home/seth295c/sycl_workspace/llvm/build/bin/../include/sycl/CL/sycl.hpp:11:
In file included from /home/seth295c/sycl_workspace/llvm/build/bin/../include/sycl/CL/sycl/accessor.hpp:11:
/home/seth295c/sycl_workspace/llvm/build/bin/../include/sycl/CL/__spirv/spirv_types.hpp:13:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
```
Importing cstddef into normal c++ source file and compiling it with gcc works without any issue.

**Comment by zjin-lcf** [comment]
GCC_TOOLCHAIN = "/auto/software/gcc/x86_64/gcc-9.1.0/"

"which gcc" shows /auto/software/gcc/x86_64/gcc-9.1.0/bin/gcc

So you might change the path for '--gcc-toolchain='.  

You are welcome.

**Comment by ThielemannSe** [comment]
Thanks, this worked again and compilation process works without an error. 
Now when I try to run the compiled example I get an error that the Intels Math Library ```liibmf.so``` cannot be found. 
Setting the ```LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DPCPP_HOME/llvm/build/lib``` doesn't work. Shouldn't the library be in there?

**Comment by JackAKirk** [comment]
> Thanks, this worked again and compilation process works without an error. Now when I try to run the compiled example I get an error that the Intels Math Library `libimf.so` cannot be found. Setting the `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DPCPP_HOME/llvm/build/lib` doesn't work. Shouldn't the library be in there?

`libimf.so` is an Intel math library. It is not located in my local non-packaged build of DPC++, but it is located in a packaged build of DPC++ with default location as described here, https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-dpcpp-compiler/top.html:

```
/opt/intel/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64/libimf.so
```

Unfortunately there is not yet a packaged DPC++ release including the CUDA backend. In the meantime if you require using libimf.so with the CUDA backend DPC++ build you could consider loading another intel compiler module such as icpc etc. I think that such a module is likely to also have this missing Intel math library.
