### ISSUE TITLE
Build Erros sycl branch

### ISSUE THREAD

**Issue by andreagen0r** [intel/llvm#7597]
**Describe the bug**
I pulled sycl brach today, but I'm getting an error when building

**To Reproduce**
```shell
python3 $DPCPP_HOME/llvm/buildbot/configure.py --cuda -t debug --cmake-gen "Ninja" --use-lld
python3 $DPCPP_HOME/llvm/buildbot/compile.py 
```

**Environment (please complete the following information):**

- OS: Linux Kubuntu22.04
- Target device and vendor: NVIDIA GTX 960
- DPC++ version: clang version 16.0.0 (https://github.com/intel/llvm b84f0b22674374a7e0a4270e31938a8ce98f5f17)

**Additional context**

``` shell
FAILED: lib/libsycl-fallback-cstring.spv /home/andreagenor/sycl_workspace/llvm/build/lib/libsycl-fallback-cstring.spv 
cd /home/andreagenor/sycl_workspace/llvm/build/tools/libdevice && /home/andreagenor/sycl_workspace/llvm/build/bin/clang-16 -fsycl-device-only -fno-sycl-use-bitcode -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2020 -fno-sycl-libspirv -fno-bundle-offload-arch -nocudalib /home/andreagenor/sycl_workspace/llvm/libdevice/fallback-cstring.cpp -o /home/andreagenor/sycl_workspace/llvm/build/./lib/libsycl-fallback-cstring.spv
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64-unknown-unknown' [-Woption-ignored]
clang-16: warning: argument unused during compilation: '-fno-bundle-offload-arch' [-Wunused-command-line-argument]
In file included from /home/andreagenor/sycl_workspace/llvm/libdevice/fallback-cstring.cpp:9:
/home/andreagenor/sycl_workspace/llvm/libdevice/wrapper.h:16:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
[2940/3032] Generating ../../lib/libsycl-fallback-cassert.o
FAILED: lib/libsycl-fallback-cassert.o /home/andreagenor/sycl_workspace/llvm/build/lib/libsycl-fallback-cassert.o 
cd /home/andreagenor/sycl_workspace/llvm/build/tools/libdevice && /home/andreagenor/sycl_workspace/llvm/build/bin/clang-16 -fsycl -c -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2020 -fno-sycl-libspirv -fno-bundle-offload-arch -nocudalib -fsycl-targets=spir64_x86_64-unknown-unknown,spir64_gen-unknown-unknown,spir64_fpga-unknown-unknown,spir64-unknown-unknown,nvptx64-nvidia-cuda -fno-sycl-instrument-device-code /home/andreagenor/sycl_workspace/llvm/libdevice/fallback-cassert.cpp -o /home/andreagenor/sycl_workspace/llvm/build/./lib/libsycl-fallback-cassert.o
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64_x86_64-unknown-unknown' [-Woption-ignored]
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64_gen-unknown-unknown' [-Woption-ignored]
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64_fpga-unknown-unknown' [-Woption-ignored]
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64-unknown-unknown' [-Woption-ignored]
clang-16: warning: '-fno-sycl-libspirv' should not be used with target 'nvptx64-nvidia-cuda'; libspirv is required for correct behavior [-Wno-libspirv-hip-cuda]
clang-16: warning: CUDA version 11.7 is only partially supported [-Wunknown-cuda-version]
In file included from /home/andreagenor/sycl_workspace/llvm/libdevice/fallback-cassert.cpp:9:
/home/andreagenor/sycl_workspace/llvm/libdevice/atomic.hpp:10:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.
[2941/3032] Generating ../../lib/libsycl-fallback-complex.o
FAILED: lib/libsycl-fallback-complex.o /home/andreagenor/sycl_workspace/llvm/build/lib/libsycl-fallback-complex.o 
cd /home/andreagenor/sycl_workspace/llvm/build/tools/libdevice && /home/andreagenor/sycl_workspace/llvm/build/bin/clang-16 -fsycl -c -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2020 -fno-sycl-libspirv -fno-bundle-offload-arch -nocudalib -fsycl-targets=spir64_x86_64-unknown-unknown,spir64_gen-unknown-unknown,spir64_fpga-unknown-unknown,spir64-unknown-unknown,nvptx64-nvidia-cuda /home/andreagenor/sycl_workspace/llvm/libdevice/fallback-complex.cpp -o /home/andreagenor/sycl_workspace/llvm/build/./lib/libsycl-fallback-complex.o
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64_x86_64-unknown-unknown' [-Woption-ignored]
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64_gen-unknown-unknown' [-Woption-ignored]
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64_fpga-unknown-unknown' [-Woption-ignored]
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64-unknown-unknown' [-Woption-ignored]
clang-16: warning: '-fno-sycl-libspirv' should not be used with target 'nvptx64-nvidia-cuda'; libspirv is required for correct behavior [-Wno-libspirv-hip-cuda]
clang-16: warning: CUDA version 11.7 is only partially supported [-Wunknown-cuda-version]
/home/andreagenor/sycl_workspace/llvm/libdevice/fallback-complex.cpp:12:10: fatal error: 'cmath' file not found
#include <cmath>
         ^~~~~~~
1 error generated.
[2942/3032] Generating ../../lib/libsycl-native-bfloat16.spv
FAILED: lib/libsycl-native-bfloat16.spv /home/andreagenor/sycl_workspace/llvm/build/lib/libsycl-native-bfloat16.spv 
cd /home/andreagenor/sycl_workspace/llvm/build/tools/libdevice && /home/andreagenor/sycl_workspace/llvm/build/bin/clang-16 -fsycl-device-only -fno-sycl-use-bitcode -Wno-sycl-strict -Wno-undefined-internal -sycl-std=2020 -fno-sycl-libspirv -fno-bundle-offload-arch -nocudalib /home/andreagenor/sycl_workspace/llvm/libdevice/bfloat16_wrapper.cpp -o /home/andreagenor/sycl_workspace/llvm/build/./lib/libsycl-native-bfloat16.spv
clang-16: warning: ignoring '-fno-sycl-libspirv' option as it is not currently supported for target 'spir64-unknown-unknown' [-Woption-ignored]
clang-16: warning: argument unused during compilation: '-fno-bundle-offload-arch' [-Wunused-command-line-argument]
In file included from /home/andreagenor/sycl_workspace/llvm/libdevice/bfloat16_wrapper.cpp:13:
In file included from /home/andreagenor/sycl_workspace/llvm/build/bin/../include/sycl/CL/__spirv/spirv_ops.hpp:10:
/home/andreagenor/sycl_workspace/llvm/build/bin/../include/sycl/CL/__spirv/spirv_types.hpp:13:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
[2946/3032] Generating ../../lib/clc/builtins.opt.libspirv-nvptx64--.bc
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/andreagenor/sycl_workspace/llvm/buildbot/compile.py", line 71, in <module>
    ret = main()
  File "/home/andreagenor/sycl_workspace/llvm/buildbot/compile.py", line 67, in main
    return do_compile(args)
  File "/home/andreagenor/sycl_workspace/llvm/buildbot/compile.py", line 42, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/andreagenor/sycl_workspace/llvm/build', '--', 'deploy-sycl-toolchain', '-j', '8']' returned non-zero exit status 1.
```

**Comment by zjin-lcf** [comment]
sudo apt-get install build-essential

**Comment by andreagen0r** [comment]
it's installed

**Comment by emdant** [comment]
I have got the same problem, even though build-essential are installed. Any update about this? @andreagen0r

**Comment by abagusetty** [comment]
I too have seen this issue lately with the above headers while building for CUDA and HIP plugins. 

Tested with gcc/10.3.0 and gcc/11.2.0

**Comment by andreagen0r** [comment]
I found the solution, I had to change the build system from **Ninja** to **Unix Makefiles** and now all works fine

**Comment by adi-bhatl-1998** [comment]
greetings and thank you for creating this bug as I too face this issue .
how do I change the build system from Ninja to Unix Makefiles ?

**Comment by andreagen0r** [comment]
> greetings and thank you for creating this bug as I too face this issue .
> how do I change the build system from Ninja to Unix Makefiles ?

Change --cmake-gen "Ninja" to --cmake-gen "Unix Makefiles"
