### ISSUE TITLE
[SYCL][OpenMP] Release 2022-12 Build Issues

### ISSUE THREAD

**Issue by jholmen** [intel/llvm#8314]
Release 2022-12 builds fail with the error below when building with OpenMP enabled and target offloading support disabled:

```
[100%] Built target builtins.link.libspirv-tahiti-amdgcn--
[100%] Built target builtins.link.libspirv-amdgcn--amdhsa
gmake[1]: *** [CMakeFiles/Makefile2:98852: tools/sycl/CMakeFiles/deploy-sycl-toolchain.dir/rule] Error 2
gmake: *** [Makefile:22135: deploy-sycl-toolchain] Error 2
Traceback (most recent call last):
  File "./src/buildbot/compile.py", line 71, in <module>
    ret = main()
  File "./src/buildbot/compile.py", line 67, in main
    return do_compile(args)
  File "./src/buildbot/compile.py", line 42, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/autofs/nccs-svm1_home1/jholmen/22.12', '--', 'deploy-sycl-toolchain', '-j', '128']' returned non-zero exit status 2
```

Are there any known workarounds for this?

Below is a reproducer:

```
git clone -b sycl https://github.com/intel/llvm.git src
cd src
git checkout 2022-12
cd ..

module load gcc/11.2.0 rocm/5.1.0

CC=`which gcc` CXX=`which g++` python ./src/buildbot/configure.py -w $HOME --llvm-external-projects openmp --hip --hip-platform AMD --cmake-gen "Unix Makefiles" -o 22.12 --cmake-opt="-DSYCL_BUILD_PI_HIP_ROCM_DIR=/opt/rocm-5.1.0" --cmake-opt="-DLIBOMPTARGET_BUILD_AMDGPU_PLUGIN=FALSE" --cmake-opt="-DLIBOMPTARGET_BUILD_CUDA_PLUGIN=FALSE" --cmake-opt="-DLIBOMPTARGET_BUILD_DEVICERTL_BCLIB=FALSE"

python ./src/buildbot/compile.py -o 22.12
```

Below are the modules loaded:

```
Currently Loaded Modules:
  1) craype-x86-trento                       6) cray-pmi/6.1.3         11) gcc/11.2.0
  2) libfabric/1.15.0.0                      7) craype/2.7.16          12) xalt/1.3.0
  3) craype-network-ofi                      8) cray-dsmml/0.2.2       13) DefApps/default
  4) perftools-base/22.06.0                  9) cray-libsci/22.06.1.3  14) rocm/5.1.0
  5) xpmem/2.4.4-2.3_11.2__gff0e1d9.shasta  10) PrgEnv-cray/8.3.3      15) cray-mpich/8.1.17
```

**Comment by bader** [comment]
@jholmen, could you attach the full log, please? The part provided in the description doesn't show the problem.

**Comment by jholmen** [comment]
Many thanks for the quick reply.

Resolved this by installing the LLVM OpenMP libraries directly per the below:

https://github.com/intel/llvm/tree/sycl/openmp
