### ISSUE TITLE
AsyncHandler/default_async_handler.cpp fails in HIP CI

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#8555]
The AsyncHandler/default_async_handler.cpp test from [intel/llvm-test-suite](https://github.com/intel/llvm-test-suite) fails in CI with

```
UNRESOLVED: SYCL :: AsyncHandler/default_async_handler.cpp (1239 of 1243)
  ******************** TEST 'SYCL :: AsyncHandler/default_async_handler.cpp' FAILED ********************
  Exception during script execution:
  Traceback (most recent call last):
    File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/worker.py", line 76, in _execute_test_handle_errors
      result = test.config.test_format.execute(test, lit_config)
    File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/formats/shtest.py", line 27, in execute
      return lit.TestRunner.executeShTest(test, litConfig,
    File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/TestRunner.py", line 2005, in executeShTest
      return _runShTest(test, litConfig, useExternalSh, script, tmpBase)
    File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/TestRunner.py", line 1[966](https://github.com/intel/llvm/actions/runs/4312497766/jobs/7605426265#step:8:988), in _runShTest
      output = """Script:\n--\n%s\n--\nExit Code: %d\n""" % (
  TypeError: %d format: a number is required, not NoneType
```

**Comment by zjin-lcf** [comment]
Running the standalone test shows the following results. Does the test need some "try" and "catch" statements?  

CUDA
Default async_handler caught exceptions:
        Exception thrown from host_task.
terminate called without an active exception
Aborted (core dumped)

HIP:
Default async_handler caught exceptions:
        Exception thrown from host_task.
terminate called without an active exception
Aborted
